"""add activity field

Revision ID: 4b5b1953df98
Revises: d30bbb6bde0d
Create Date: 2026-08-19 17:56:37.903517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b5b1953df98'
down_revision: Union[str, Sequence[str], None] = 'd30bbb6bde0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('activities', sa.Column('field', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('activities', 'field')
    # ### end Alembic commands ###
