"""add task soft delete fields

Revision ID: a5c16f26ee2e
Revises: 4b5b1953df98
Create Date: 2026-08-20 00:11:14.972559

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5c16f26ee2e'
down_revision: Union[str, Sequence[str], None] = '4b5b1953df98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        'tasks',
        sa.Column(
            'is_deleted',
            sa.Boolean(),
            nullable=False,
            server_default=sa.false(),
        )
    )

    op.add_column(
        'tasks',
        sa.Column(
            'deleted_at',
            sa.DateTime(timezone=True),
            nullable=True,
        )
    )

    op.alter_column(
        'tasks',
        'is_deleted',
        server_default=None,
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deleted_at')
    op.drop_column('tasks', 'is_deleted')
    # ### end Alembic commands ###
