"""add reply to message relationship

Revision ID: e5cb7e39ac0b
Revises: e27461c0b12f
Create Date: 2026-08-30 22:17:49.162565

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e5cb7e39ac0b'
down_revision: Union[str, Sequence[str], None] = 'e27461c0b12f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('reply_to_message_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_messages_reply_to_message_id_messages'), 'messages', 'messages', ['reply_to_message_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_messages_reply_to_message_id_messages'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'reply_to_message_id')
    # ### end Alembic commands ###
